### PR TITLE
Add forced variation example

### PR DESCRIPTION
**Pull request by ptessier**
This change is [Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4)
- - -

- Add example to update the user id
- Add example to force a variation
- Polish UI

Let me know if you see ways to make home page more readable.

https://us02web.zoom.us/clips/share/m65vnwnskfTq6wnoNnjcCRz02idKE-uQKBZ54Iy00wyYbYbZWbHAV5F6XsW0WRFNpDHozsNJffcvDWGqdgHJvM2X.uQ2yGVUwOKrbQjs3

Screenshot 2024-01-10 at 9 57 49 AM

### CODE REVIEW

**Review by darwish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mathieumg and @ptessier)

___
*[`packages/react/src/pages/home.tsx` line 122 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-NnnxzvDBEMl5upFl-wO:-NnnxzvDBEMl5upFl-wP:b6fdrae) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L122)):*
> ```XML
>             placeholder="variation key"
>             value={variationKey}
>             onChange={(e) => setVariationKey(e.target.value)}
> ```

Q: If I set the variation key to "treatment" or "control" should it change the results of the experiment assignment?

**Comment by ptessier** [comment]
*[`packages/react/src/pages/home.tsx` line 122 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-NnnxzvDBEMl5upFl-wO:-Nno01kBBY429rtFfRXU:b-rudkqc) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L122)):*
<details><summary><i>Previously, darwish (Mike Darwish) wrote…</i></summary><blockquote>

Q: If I set the variation key to "treatment" or "control" should it change the results of the experiment assignment?
</blockquote></details>

It should change the assignment yes
 At least, it should write that "reason: forced variation found"

**Review by darwish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mathieumg and @ptessier)

___
*[`packages/react/src/pages/home.tsx` line 122 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-NnnxzvDBEMl5upFl-wO:-Nno1WYLEyiX9wOX-JDV:b-tu35h2) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L122)):*
<details><summary><i>Previously, ptessier (Philippe Tessier) wrote…</i></summary><blockquote>

It should change the assignment yes
 At least, it should write that "reason: forced variation found"
</blockquote></details>

Doesn't seem to work for me (on a fresh repo clone at least)

**Review by darwish — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4)* status: all files reviewed, 2 unresolved discussions (waiting on @mathieumg and @ptessier)

___
*[`packages/react/src/pages/home.tsx` line 121 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-Nno3ruG2pk7wmZ8SxqB:-Nno3ruG2pk7wmZ8SxqC:b-wko1hp) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L121)):*
> ```XML
>             type="input"
>             placeholder="variation key"
>             value={variationKey}
> ```

Nit (UX): it's a bit annoying that you have to retype the experiment and variation keys each time you want to play around with the forced variations.
___
*[`packages/react/src/pages/home.tsx` line 122 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-NnnxzvDBEMl5upFl-wO:-Nno3JnLAs-KhKCoDs0E:b-g1sczr) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L122)):*
<details><summary><i>Previously, darwish (Mike Darwish) wrote…</i></summary><blockquote>

Doesn't seem to work for me (on a fresh repo clone at least)
</blockquote></details>

Nvm, wasn't built properly

**Review by kdziuba-mx — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4)* status: all files reviewed, 2 unresolved discussions (waiting on @darwish, @mathieumg, and @ptessier)

___
*[`packages/react/src/pages/home.tsx` line 121 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-Nno3ruG2pk7wmZ8SxqB:-Nno57H3CMV_blnu7weB:b32v57) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L121)):*
<details><summary><i>Previously, darwish (Mike Darwish) wrote…</i></summary><blockquote>

Nit (UX): it's a bit annoying that you have to retype the experiment and variation keys each time you want to play around with the forced variations.
</blockquote></details>

+1

**Review by ptessier — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mathieumg)

___
*[`packages/react/src/pages/home.tsx` line 121 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-Nno3ruG2pk7wmZ8SxqB:-NnoLWFVCaGILvXOOa2V:b-4u8ag) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L121)):*
<details><summary><i>Previously, kdziuba-mx (Kostiantyn Dziuba) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Yeah maybe I can just put a force control or force treatment button?

**Comment by ptessier** [comment]
*[`packages/react/src/pages/home.tsx` line 121 at r1](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-Nno3ruG2pk7wmZ8SxqB:-NnoYMzC3WybsudN6_iS:b9pfwdc) ([raw file](https://github.com/MaintainX/react-meetup-ab-testing/blob/1e29c13d64969c40bbc1ad4358def185d602fc4b/packages/react/src/pages/home.tsx#L121)):*
<details><summary><i>Previously, ptessier (Philippe Tessier) wrote…</i></summary><blockquote>

Yeah maybe I can just put a force control or force treatment button?
</blockquote></details>

**Review by ptessier — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @darwish, @kdziuba-mx, and @mathieumg)

**Review by darwish — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MaintainX/react-meetup-ab-testing/4#-:-NnoZml4EotQpEXGwEqX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kdziuba-mx and @mathieumg)

**Pull request merged**
